services:
  - type: web
    name: wiseflix-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python WiseFlix.py
    envVars:
      - key: TMDB_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: wiseflix-db
          type: postgres
      - key: WEBHOOK_URL
        generateValue: true
      - key: DISABLE_RATE_LIMITER
        value: "0"
